packages:
  - 'web/*'

catalog:
  '@samatech/postcss-basics': 0.7.4
  '@samatech/vue-store': 0.7.0
  '@samatech/vue-components': 1.2.6
  'date-fns': 4.1.0
  'jwt-decode': 4.0.0
  postcss: 8.5.1
  vue: 3.5.13
  vue-router: 4.5.0
  vite: 6.1.0
  typescript: 5.7.3
  '@floating-ui/vue': 1.1.6
  '@samatech/fetch-api': 0.12.1
  '@types/node': 20.15.0
  '@vitejs/plugin-vue': 5.2.1
  terser: 5.38.1
