import { ICharacterInfo, ICharacterSet } from '@learn-chinese/types'

const info = (p: string, z: string, e?: string, audio?: string): ICharacterInfo => {
  return { p, z, e, audio }
}

export const hsk1: ICharacterSet = {
  愛: info('ài', 'ㄞˋ', 'love'),
  八: info('bā', 'ㄅㄚ', 'eight'),
  爸爸: info('bà ba', 'ㄅㄚˋ ˙ㄅㄚ', 'father'),
  杯子: info('bēi zi', 'ㄅㄟ ˙ㄗ', 'cup'),
  北京: info('běi jīng', 'ㄅㄟˇ ㄐㄧㄥ', 'Beijing'),
  本: info('běn', 'ㄅㄣˇ', 'measure word for books'),
  不客氣: info('bú kè qi', 'ㄅㄨˋ ㄎㄜˋ ㄑㄧˋ', "you're welcome"),
  不: info('bù', 'ㄅㄨˋ', 'not'),
  菜: info('cài', 'ㄘㄞˋ', 'dish; vegetable'),
  茶: info('chá', 'ㄔㄚˊ', 'tea'),
  吃: info('chī', 'ㄔ', 'eat'),
  出租車: info('chū zū chē', 'ㄔㄨ ㄗㄨ ㄔㄜ', 'taxi'),
  打電話: info('dǎ diàn huà', 'ㄉㄚˇ ㄉㄧㄢˋ ㄏㄨㄚˋ', 'make a phone call'),
  大: info('dà', 'ㄉㄚˋ', 'big'),
  的: info('de', '˙ㄉㄜ', 'possessive particle'),
  點: info('diǎn', 'ㄉㄧㄢˇ', "o'clock"),
  電腦: info('diàn nǎo', 'ㄉㄧㄢˋ ㄋㄠˇ', 'computer'),
  電視: info('diàn shì', 'ㄉㄧㄢˋ ㄕˋ', 'television'),
  電影: info('diàn yǐng', 'ㄉㄧㄢˋ ㄧㄥˇ', 'movie'),
  東西: info('dōng xi', 'ㄉㄨㄥ ˙ㄒㄧ', 'thing'),
  都: info('dōu', 'ㄉㄡ', 'all'),
  讀: info('dú', 'ㄉㄨˊ', 'read'),
  對不起: info('duì bu qǐ', 'ㄉㄨㄟˋ ˙ㄅㄨ ㄑㄧˇ', 'sorry'),
  多: info('duō', 'ㄉㄨㄛ', 'many; much'),
  多少: info('duō shǎo', 'ㄉㄨㄛ ㄕㄠˇ', 'how many; how much'),
  兒子: info('ér zi', 'ㄦˊ ㄗˇ', 'son'),
  二: info('èr', 'ㄦˋ', 'two'),
  飯店: info('fàn diàn', 'ㄈㄢˋ ㄉㄧㄢˋ', 'hotel; restaurant'),
  飛機: info('fēi jī', 'ㄈㄟ ㄐㄧ', 'airplane'),
  分鍾: info('fēn zhōng', 'ㄈㄣ ㄓㄨㄥ', 'minute'),
  高興: info('gāo xìng', 'ㄍㄠ ㄒㄧㄥˋ', 'happy'),
  個: info('gè', 'ㄍㄜˋ', 'general measure word'),
  工作: info('gōng zuò', 'ㄍㄨㄥ ㄗㄨㄛˋ', 'work'),
  狗: info('gǒu', 'ㄍㄡˇ', 'dog'),
  漢語: info('hàn yǔ', 'ㄏㄢˋ ㄩˇ', 'Chinese language'),
  好: info('hǎo', 'ㄏㄠˇ', 'good'),
  號: info('hào', 'ㄏㄠˋ', 'date; number'),
  喝: info('hē', 'ㄏㄜ', 'drink'),
  和: info('hé', 'ㄏㄜˊ', 'and'),
  很: info('hěn', 'ㄏㄣˇ', 'very'),
  後面: info('hòu miàn', 'ㄏㄡˋ ㄇㄧㄢˋ', 'back; behind'),
  回: info('huí', 'ㄏㄨㄟˊ', 'return'),
  會: info('huì', 'ㄏㄨㄟˋ', 'can; will'),
  幾: info('jǐ', 'ㄐㄧˇ', 'how many; several'),
  家: info('jiā', 'ㄐㄧㄚ', 'home; family'),
  叫: info('jiào', 'ㄐㄧㄠˋ', 'call; be called'),
  今天: info('jīn tiān', 'ㄐㄧㄣ ㄊㄧㄢ', 'today'),
  九: info('jiǔ', 'ㄐㄧㄡˇ', 'nine'),
  開: info('kāi', 'ㄎㄞ', 'open; drive'),
  看: info('kàn', 'ㄎㄢˋ', 'look; see; watch'),
  看見: info('kàn jiàn', 'ㄎㄢˋ ˙ㄐㄧㄢ', 'see; catch sight of'),
  塊: info('kuài', 'ㄎㄨㄞˋ', 'yuan (money)'),
  來: info('lái', 'ㄌㄞˊ', 'come'),
  老師: info('lǎo shī', 'ㄌㄠˇ ㄕ', 'teacher'),
  了: info('le', '˙ㄌㄜ', 'aspect particle'),
  冷: info('lěng', 'ㄌㄥˇ', 'cold'),
  裡: info('lǐ', 'ㄌㄧˇ', 'inside'),
  六: info('liù', 'ㄌㄧㄡˋ', 'six'),
  嗎: info('ma', '˙ㄇㄚ', 'question particle'),
  媽媽: info('mā ma', 'ㄇㄚ ˙ㄇㄚ', 'mother'),
  買: info('mǎi', 'ㄇㄞˇ', 'buy'),
  貓: info('māo', 'ㄇㄠ', 'cat'),
  沒關系: info('méi guān xi', 'ㄇㄛˋ ㄍㄨㄢ ㄒㄧˋ', "it doesn't matter"),
  沒有: info('méi yǒu', 'ㄇㄟˊ ㄧㄡˇ', "don't have"),
  米飯: info('mǐ fàn', 'ㄇㄧˇ ㄈㄢˋ', 'rice'),
  名字: info('míng zi', 'ㄇㄧㄥˊ ˙ㄗ', 'name'),
  明天: info('míng tiān', 'ㄇㄧㄥˊ ㄊㄧㄢ', 'tomorrow'),
  哪: info('nǎ', 'ㄋㄚˇ', 'which'),
  哪兒: info('nǎ er', 'ㄋㄚˇ ㄦˊ', 'where'),
  那: info('nà', 'ㄋㄚˋ', 'that'),
  呢: info('ne', '˙ㄋㄜ', 'question particle'),
  能: info('néng', 'ㄋㄥˊ', 'can'),
  你: info('nǐ', 'ㄋㄧˇ', 'you'),
  年: info('nián', 'ㄋㄧㄢˊ', 'year'),
  女兒: info('nǚ ér', 'ㄋㄩˇ ㄦˊ', 'daughter'),
  朋友: info('péng you', 'ㄆㄥˊ ㄧㄡˇ', 'friend'),
  漂亮: info('piào liang', 'ㄆㄧㄠˋ ˙ㄌㄧㄤ', 'beautiful'),
  蘋果: info('píng guǒ', 'ㄆㄧㄥˊ ㄍㄨㄛˇ', 'apple'),
  七: info('qī', 'ㄑㄧ', 'seven'),
  前面: info('qián miàn', 'ㄑㄧㄢˊ ㄇㄧㄢˋ', 'front'),
  錢: info('qián', 'ㄑㄧㄢˊ', 'money'),
  請: info('qǐng', 'ㄑㄧㄥˇ', 'please; invite'),
  去: info('qù', 'ㄑㄩˋ', 'go'),
  熱: info('rè', 'ㄖㄜˋ', 'hot'),
  人: info('rén', 'ㄖㄣˊ', 'person'),
  認識: info('rèn shi', 'ㄖㄣˋ ˙ㄕ', 'know; recognize'),
  三: info('sān', 'ㄙㄢ', 'three'),
  商店: info('shāng diàn', 'ㄕㄤ ㄉㄧㄢˋ', 'shop'),
  上: info('shàng', 'ㄕㄤˋ', 'on; above'),
  上午: info('shàng wǔ', 'ㄕㄤˋ ㄨˇ', 'morning'),
  少: info('shǎo', 'ㄕㄠˇ', 'few; little'),
  誰: info('shéi', 'ㄕㄟˊ', 'who'),
  什麼: info('shén me', 'ㄕㄣˊ ˙ㄇㄜㄕㄜˊ ˙ㄇㄜ', 'what'),
  十: info('shí', 'ㄕˊ', 'ten'),
  時候: info('shí hou', 'ㄕˊ ㄏㄡˋ', 'time; when'),
  是: info('shì', 'ㄕˋ', 'is; are'),
  書: info('shū', 'ㄕㄨ', 'book'),
  水: info('shuǐ', 'ㄕㄨㄟˇ', 'water'),
  水果: info('shuǐguǒ', 'ㄕㄨㄟˇ ㄍㄨㄛˇ', 'fruit'),
  睡覺: info('shuì jiào', 'ㄕㄨㄟˋ ㄐㄧㄠˋ', 'sleep'),
  說: info('shuō', 'ㄕㄨㄛ', 'say; speak'),
  四: info('sì', 'ㄙˋ', 'four'),
  歲: info('suì', 'ㄙㄨㄟˋ', 'year (of age)'),
  他: info('tā', 'ㄊㄚ', 'he'),
  她: info('tā', 'ㄊㄚ', 'she'),
  太: info('tài', 'ㄊㄞˋ', 'too'),
  天氣: info('tiān qì', 'ㄊㄧㄢ ㄑㄧˋ', 'weather'),
  聽: info('tīng', 'ㄊㄧㄥ', 'listen'),
  同學: info('tóng xué', 'ㄊㄨㄥˊ ㄒㄩㄝˊ', 'classmate'),
  喂: info('wèi', 'ㄨㄟˋ', 'hello'),
  我: info('wǒ', 'ㄨㄛˇ', 'I; me'),
  我們: info('wǒ men', 'ㄨㄛˇ ˙ㄇㄣ', 'we'),
  五: info('wǔ', 'ㄨˇ', 'five'),
  喜歡: info('xǐ huan', 'ㄒㄧˇ ㄏㄨㄢ', 'like'),
  下: info('xià', 'ㄒㄧㄚˋ', 'down; below'),
  下午: info('xià wǔ', 'ㄒㄧㄚˋ ㄨˇ', 'afternoon'),
  下雨: info('xià yǔ', 'ㄒㄧㄚˋ ㄩˇ', 'rain'),
  先生: info('xiān sheng', 'ㄒㄧㄢ ㄕㄥ', 'Mr.; sir'),
  現在: info('xiàn zài', 'ㄒㄧㄢˋ ㄗㄞˋ', 'now'),
  想: info('xiǎng', 'ㄒㄧㄤˇ', 'think; want'),
  小: info('xiǎo', 'ㄒㄧㄠˇ', 'small'),
  小姐: info('xiǎo jie', 'ㄒㄧㄠˇ ㄐㄧㄝˇ', 'Miss; Ms.'),
  些: info('xiē', 'ㄒㄧㄝ', 'some'),
  寫: info('xiě', 'ㄒㄧㄝˇ', 'write'),
  謝謝: info('xiè xie', 'ㄒㄧㄝˋ ˙ㄒㄧㄝ', 'thank you'),
  星期: info('xīng qī', 'ㄒㄧㄥ ㄑㄧˊ', 'week'),
  學生: info('xué sheng', 'ㄒㄩㄝˊ ㄕㄥ', 'student'),
  學習: info('xué xí', 'ㄒㄩㄝˊ ㄒㄧˊ', 'study'),
  學校: info('xué xiào', 'ㄒㄩㄝˊ ㄒㄧㄠˋ', 'school'),
  一: info('yī', 'ㄧ', 'one'),
  一點兒: info('yī diǎn er', 'ㄧ ㄉㄧㄢˇㄦ (變)ㄧˋ ㄉㄧㄚˇㄦ', 'a little'),
  醫生: info('yī shēng', 'ㄧ ㄕㄥ', 'doctor'),
  醫院: info('yī yuàn', 'ㄧ ㄩㄢˋ', 'hospital'),
  衣服: info('yī fu', 'ㄧ ˙ㄈㄨ', 'clothes'),
  椅子: info('yǐ zi', 'ㄧˇ ˙ㄗ', 'chair'),
  有: info('yǒu', 'ㄧㄡˇ', 'have'),
  月: info('yuè', 'ㄩㄝˋ', 'month'),
  再見: info('zài jiàn', 'ㄗㄞˋ ㄐㄧㄢˋ', 'goodbye'),
  在: info('zài', 'ㄗㄞˋ', 'at; in'),
  怎麼: info('zěn me', 'ㄗㄣˇ ˙ㄇㄜ', 'how'),
  怎麼樣: info('zěn me yàng', 'ㄗㄣˇ ˙ㄇㄜ ㄧㄤˋ', 'how about'),
  這: info('zhè', 'ㄓㄜˋ', 'this'),
  中國: info('zhōng guó', 'ㄓㄨㄥ ㄍㄨㄛˊ', 'China'),
  中午: info('zhōng wǔ', 'ㄓㄨㄥ ㄨˇ', 'noon'),
  住: info('zhù', 'ㄓㄨˋ', 'live'),
  桌子: info('zhuō zi', 'ㄓㄨㄛ ˙ㄗ', 'table; desk'),
  字: info('zì', 'ㄗˋ', 'character; word'),
  昨天: info('zuó tiān', 'ㄗㄨㄛˊ ㄊㄧㄢ', 'yesterday'),
  做: info('zuò', 'ㄗㄨㄛˋ', 'do; make'),
  坐: info('zuò', 'ㄗㄨㄛˋ', 'sit'),
}
