import { IPhraseSection } from '@learn-chinese/types'

// Common everyday phrases in traditional (Taiwanese) Mandarin.
// To add a phrase, drop a new entry into the relevant section (or add a new
// section). Each phrase needs `zh` (traditional characters), `en` (meaning),
// and `pinyin` (tone marks). Audio is generated on demand via the backend.
export const phraseSections: IPhraseSection[] = [
  {
    id: 'greetings',
    title: 'Basic greetings',
    phrases: [
      { zh: '早安', en: 'Good morning', pinyin: 'zǎo ān' },
      { zh: '午安', en: 'Good afternoon', pinyin: 'wǔ ān' },
      { zh: '晚安', en: 'Good night', pinyin: 'wǎn ān' },
      { zh: '好久不見', en: 'Long time no see', pinyin: 'hǎo jiǔ bù jiàn' },
      { zh: '最近好嗎？', en: 'How have you been?', pinyin: 'zuì jìn hǎo ma?' },
      { zh: '你吃飽了嗎？', en: 'Have you eaten?', pinyin: 'nǐ chī bǎo le ma?' },
      { zh: '辛苦了', en: 'You worked hard', pinyin: 'xīn kǔ le' },
      { zh: '慢走', en: 'Take care', pinyin: 'màn zǒu' },
      { zh: '明天見', en: 'See you tomorrow', pinyin: 'míng tiān jiàn' },
      { zh: '下次見', en: 'See you next time', pinyin: 'xià cì jiàn' },
      { zh: '等一下見', en: 'See you in a bit', pinyin: 'děng yī xià jiàn' },
    ],
  },
  {
    id: 'thanks',
    title: 'Thanks and polite phrases',
    phrases: [
      { zh: '感謝', en: 'Thanks / appreciate it', pinyin: 'gǎn xiè' },
      { zh: '太感謝了', en: 'Thanks so much', pinyin: 'tài gǎn xiè le' },
      { zh: '不客氣', en: "You're welcome", pinyin: 'bù kè qì' },
      { zh: '不會', en: "No problem / you're welcome", pinyin: 'bù huì' },
      { zh: '沒事', en: "It's nothing", pinyin: 'méi shì' },
      {
        zh: '麻煩你了',
        en: 'Sorry to trouble you / thanks for helping',
        pinyin: 'má fán nǐ le',
      },
      { zh: '辛苦你了', en: 'Thanks for your effort', pinyin: 'xīn kǔ nǐ le' },
      { zh: '拜託你了', en: "Please / I'm counting on you", pinyin: 'bài tuō nǐ le' },
      { zh: '可以嗎？', en: 'Is that okay?', pinyin: 'kě yǐ ma?' },
      { zh: '方便嗎？', en: 'Is it convenient?', pinyin: 'fāng biàn ma?' },
      { zh: '沒問題', en: 'No problem', pinyin: 'méi wèn tí' },
      { zh: '可以啊', en: 'Sure', pinyin: 'kě yǐ a' },
    ],
  },
  {
    id: 'apologies',
    title: 'Apologies / attention',
    phrases: [
      { zh: '不好意思', en: 'Excuse me / sorry', pinyin: 'bù hǎo yì si' },
      { zh: '抱歉', en: 'Sorry', pinyin: 'bào qiàn' },
      { zh: '對不起', en: 'Sorry', pinyin: 'duì bù qǐ' },
      {
        zh: '不好意思，借過一下',
        en: 'Excuse me, let me pass',
        pinyin: 'bù hǎo yì si, jiè guò yī xià',
      },
      {
        zh: '不好意思，請問一下',
        en: 'Excuse me, may I ask?',
        pinyin: 'bù hǎo yì si, qǐng wèn yī xià',
      },
      {
        zh: '不好意思，打擾一下',
        en: 'Sorry to bother you',
        pinyin: 'bù hǎo yì si, dǎ rǎo yī xià',
      },
      { zh: '我不是故意的', en: "I didn't mean to", pinyin: 'wǒ bù shì gù yì de' },
      { zh: '沒關係', en: "It's okay", pinyin: 'méi guān xì' },
      { zh: '沒事啦', en: "It's fine", pinyin: 'méi shì la' },
      { zh: '不用擔心', en: "Don't worry", pinyin: 'bù yòng dān xīn' },
      { zh: '我搞錯了', en: 'I made a mistake', pinyin: 'wǒ gǎo cuò le' },
      { zh: '我忘記了', en: 'I forgot', pinyin: 'wǒ wàng jì le' },
      { zh: '我遲到了', en: "I'm late", pinyin: 'wǒ chí dào le' },
      {
        zh: '讓你久等了',
        en: 'Sorry for keeping you waiting',
        pinyin: 'ràng nǐ jiǔ děng le',
      },
      {
        zh: '不好意思，我中文不太好',
        en: "Sorry, my Chinese isn't very good",
        pinyin: 'bù hǎo yì si, wǒ zhōng wén bù tài hǎo',
      },
    ],
  },
  {
    id: 'reactions',
    title: 'Common reactions',
    phrases: [
      { zh: '真的嗎？', en: 'Really?', pinyin: 'zhēn de ma?' },
      { zh: '真的假的？', en: 'Seriously?', pinyin: 'zhēn de jiǎ de?' },
      { zh: '原來如此', en: 'I see', pinyin: 'yuán lái rú cǐ' },
      { zh: '這樣喔', en: 'Oh, like that', pinyin: 'zhè yàng ō' },
      { zh: '難怪', en: 'No wonder', pinyin: 'nán guài' },
      { zh: '太好了', en: "That's great", pinyin: 'tài hǎo le' },
      { zh: '太誇張了', en: 'Unbelievable', pinyin: 'tài kuā zhāng le' },
      { zh: '好酷喔', en: 'So cool', pinyin: 'hǎo kù ō' },
      { zh: '好可愛', en: 'So cute', pinyin: 'hǎo kě ài' },
      { zh: '好漂亮', en: 'So pretty', pinyin: 'hǎo piào liàng' },
      { zh: '好好笑', en: 'So funny', pinyin: 'hǎo hǎo xiào' },
      { zh: '好厲害', en: 'So impressive', pinyin: 'hǎo lì hài' },
      { zh: '好可怕', en: 'So scary', pinyin: 'hǎo kě pà' },
      { zh: '好煩喔', en: 'So annoying', pinyin: 'hǎo fán ō' },
      { zh: '好累喔', en: 'So tired', pinyin: 'hǎo lèi ō' },
      { zh: '還好', en: 'Not bad', pinyin: 'hái hǎo' },
      { zh: '還可以', en: "It's alright", pinyin: 'hái kě yǐ' },
      { zh: '差不多', en: 'Close enough', pinyin: 'chà bù duō' },
      { zh: '沒差', en: "Doesn't matter", pinyin: 'méi chà' },
      { zh: '隨便', en: 'Whatever / up to you', pinyin: 'suí biàn' },
    ],
  },
]
