apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-api
  labels:
    component: learn-api
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: learn-api
      tier: backend
  template:
    metadata:
      labels:
        component: learn-api
        tier: backend
    spec:
      containers:
        - name: learn-api
          image: learn-api.prod
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: learn-api-config
            - configMapRef:
                name: db-app-config
            - configMapRef:
                name: sendgrid-config
