import { IUnit } from '@learn-chinese/types'

export const restaurantUnit: IUnit = {
  id: 'restaurant',
  title: 'Restaurant',
  titleChinese: '餐廳',
  description:
    'Ordering food, reading menus, and common phrases for dining out in Taiwan.',
  icon: '🍜',
  color: '#c2410c',
  phrases: [
    { id: 'caidan', chinese: '菜單', pinyin: 'càidān', english: 'menu' },
    {
      id: 'fuwusheng',
      chinese: '服務生',
      pinyin: 'fúwùshēng',
      english: 'waiter / server',
    },
    { id: 'diancian', chinese: '點餐', pinyin: 'diǎncān', english: 'to order food' },
    { id: 'maidan', chinese: '買單', pinyin: 'mǎidān', english: 'the bill / check' },
    { id: 'waidai', chinese: '外帶', pinyin: 'wàidài', english: 'takeout / to go' },
    { id: 'neiyong', chinese: '內用', pinyin: 'nèiyòng', english: 'dine in' },
    {
      id: 'haochi',
      chinese: '好吃',
      pinyin: 'hǎochī',
      english: 'delicious / tastes good',
    },
    { id: 'la', chinese: '辣', pinyin: 'là', english: 'spicy' },
    { id: 'bula', chinese: '不辣', pinyin: 'bùlà', english: 'not spicy' },
    {
      id: 'niuroumian',
      chinese: '牛肉麵',
      pinyin: 'niúròumiàn',
      english: 'beef noodle soup',
    },
    {
      id: 'xiaolongbao',
      chinese: '小籠包',
      pinyin: 'xiǎolóngbāo',
      english: 'soup dumplings',
    },
    {
      id: 'zhenzhu',
      chinese: '珍珠奶茶',
      pinyin: 'zhēnzhūnǎichá',
      english: 'bubble tea',
    },
    { id: 'jiwei', chinese: '幾位', pinyin: 'jǐ wèi', english: 'how many people' },
    { id: 'weizi', chinese: '位子', pinyin: 'wèizi', english: 'seat / table' },
    {
      id: 'duoshao',
      chinese: '多少錢',
      pinyin: 'duōshǎoqián',
      english: 'how much does it cost',
    },
  ],
  sentences: [
    {
      id: 's1',
      template: '請給我菜___。',
      answer: '單',
      english: 'Please give me the menu.',
      distractors: ['帶', '用', '餐'],
    },
    {
      id: 's2',
      template: '我要___帶。',
      answer: '外',
      english: 'I want takeout.',
      distractors: ['內', '好', '多'],
    },
    {
      id: 's3',
      template: '服務生，___單！',
      answer: '買',
      english: 'Waiter, the bill please!',
      distractors: ['菜', '外', '點'],
    },
    {
      id: 's4',
      template: '這個很好___！',
      answer: '吃',
      english: 'This is very delicious!',
      distractors: ['辣', '少', '多'],
    },
    {
      id: 's5',
      template: '有___子嗎？',
      answer: '位',
      english: 'Are there any seats available?',
      distractors: ['幾', '多', '好'],
    },
    {
      id: 's6',
      template: '兩位，___用。',
      answer: '內',
      english: 'Two people, dine in.',
      distractors: ['外', '好', '點'],
    },
  ],
  orderPhrases: [
    {
      id: 'o1',
      words: ['我', '要', '點', '餐'],
      english: 'I want to order food',
      distractors: ['吃', '買', '好'],
    },
    {
      id: 'o2',
      words: ['請', '給', '我', '菜單'],
      english: 'Please give me the menu',
      distractors: ['好', '很', '用'],
    },
    {
      id: 'o3',
      words: ['外帶', '還是', '內用'],
      english: 'Takeout or dine in?',
      distractors: ['好吃', '謝謝', '服務生'],
    },
    {
      id: 'o4',
      words: ['這個', '多少', '錢'],
      english: 'How much is this?',
      distractors: ['好吃', '要', '我'],
    },
  ],
}
