apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: learn-api
requires:
  - path: ./skaffold.db.yaml
build:
  local:
    useBuildkit: true
    push: false
  artifacts:
    - image: learn-api.dev
      context: ../
      sync:
        manual:
          - src: 'backend/learn-api/src/**/*'
            dest: '/usr/src'
          # Copy shared libs
          - src: 'backend/lib-api/src/**/*'
            dest: '/usr/src'
          - src: 'backend/lib-types/src/**/*'
            dest: '/usr/src'
          # Copy pre-built app binaries
          - src: 'backend/target/debug/learn-api*'
            dest: '/usr/src'
          - src: 'backend/target/debug/liblearn_api.*'
            dest: '/usr/src'
      docker:
        dockerfile: backend/learn-api/Dockerfile.dev
        target: dev
        buildArgs:
          # These vars can be overridden in order to manually test stg/prod environments
          S3_SECRET_ACCESS_KEY: '{{or .S3_SECRET_ACCESS_KEY "dev"}}'
          SENDGRID_API_KEY: '{{or .SENDGRID_API_KEY "dev"}}'
          APP_AUTH_SECRET: '{{or .APP_AUTH_SECRET "dev"}}'
    - image: api-test-helper.dev
      context: ../
      sync:
        manual:
          - src: 'backend/api-test-helper/src/**/*'
            dest: '/usr/src'
          - src: 'backend/lib-api/src/**/*'
            dest: '/usr/src'
          - src: 'backend/lib-types/src/**/*'
            dest: '/usr/src'
          - src: 'backend/db-app/src/**/*'
            dest: '/usr/src'
          - src: 'backend/target/debug/api-test-helper*'
            dest: '/usr/src'
          - src: 'backend/target/debug/libapi_test_helper.*'
            dest: '/usr/src'
      docker:
        dockerfile: backend/api-test-helper/Dockerfile.dev
        target: dev
        buildArgs:
          APP_AUTH_SECRET: '{{or .APP_AUTH_SECRET}}'

manifests:
  rawYaml:
    - k8s/dev/shared/*.yaml
    - k8s/dev/api/*.yaml

deploy:
  # kubeContext: rancher-desktop
  # kubeContext: docker-desktop
  kubeContext: k3d-learn-dev
  kubectl: {}
portForward:
  # Note: learn-api port-forward is handled by tools/scripts/skaffold-dev.sh
  # because skaffold incorrectly detects port 4051 as in-use (nginx binds to network interface)
  # Expose state manager app localhost connection
  - resourceType: service
    resourceName: api-test-helper
    port: 4052
