import { IZhuyinKeyInfo, IZhuyinSymbol, KeyType } from '@frontend/types'

const info = (s: IZhuyinSymbol, p: string, audio?: string): IZhuyinKeyInfo => {
  return { s, p, audio }
}

export const zhuyinSymbols: Partial<Record<KeyType, IZhuyinKeyInfo>> = {
  '1': info('ㄅ', 'b'),
  '2': info('ㄉ', 'd'),
  '3': info('ˇ', 'ˇ'),
  '4': info('ˋ', 'ˋ'),
  '5': info('ㄓ', 'zhi'),
  '6': info('ˊ', 'ˊ'),
  '7': info('˙', '˙'),
  '8': info('ㄚ', 'a'),
  '9': info('ㄞ', 'ai'),
  '0': info('ㄢ', 'an'),
  '-': info('ㄦ', 'er'),
  q: info('ㄆ', 'p'),
  w: info('ㄊ', 't'),
  e: info('ㄍ', 'g'),
  r: info('ㄐ', 'j'),
  t: info('ㄔ', 'ch'),
  y: info('ㄗ', 'z'),
  u: info('ㄧ', 'y'),
  i: info('ㄛ', 'o'),
  o: info('ㄟ', 'ei'),
  p: info('ㄣ', 'en'),
  a: info('ㄇ', 'm'),
  s: info('ㄋ', 'n'),
  d: info('ㄎ', 'k'),
  f: info('ㄑ', 'q'),
  g: info('ㄕ', 'sh'),
  h: info('ㄘ', 'c'),
  j: info('ㄨ', 'wu'),
  k: info('ㄜ', 'e'),
  l: info('ㄠ', 'ao'),
  ';': info('ㄤ', 'ang'),
  z: info('ㄈ', 'f'),
  x: info('ㄌ', 'l'),
  c: info('ㄏ', 'h'),
  v: info('ㄒ', 'x'),
  b: info('ㄖ', 'r'),
  n: info('ㄙ', 's'),
  m: info('ㄩ', 'yu'),
  ',': info('ㄝ', 'ie'),
  '.': info('ㄡ', 'ou'),
  '/': info('ㄥ', 'eng'),
}
